/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Person;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author sayu
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
     
    private Person pr;
    
    public CreateJPanel(Person pr) {
        initComponents();
        this.pr=pr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpload = new javax.swing.JButton();
        txtUploadImage = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblLicenseNo = new javax.swing.JLabel();
        txtBiometricIdentifier = new javax.swing.JTextField();
        txtFaxNo = new javax.swing.JTextField();
        lblVehicleIdentifier = new javax.swing.JLabel();
        txtTelephoneNo = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        lblDeviceIdentifier = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        lblLinkedIn = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblIp = new javax.swing.JLabel();
        lblGeographicData = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblDob = new javax.swing.JLabel();
        txtGeographicData = new javax.swing.JTextField();
        lblTelephoneNo = new javax.swing.JLabel();
        lblFaxNo = new javax.swing.JLabel();
        lblEmailID = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        txtDeviceIdentifier = new javax.swing.JTextField();
        txtIp = new javax.swing.JTextField();
        lblMedicalRecord = new javax.swing.JLabel();
        txtLinkedIn = new javax.swing.JTextField();
        txtVehicleIdentifier = new javax.swing.JTextField();
        lblHealthPlan = new javax.swing.JLabel();
        txtBankAccount = new javax.swing.JTextField();
        txtLicenseNo = new javax.swing.JTextField();
        lblBankAccount = new javax.swing.JLabel();
        txtDob = new javax.swing.JTextField();
        lblBiometricIdentifier = new javax.swing.JLabel();
        txtMedicalRecord = new javax.swing.JTextField();
        txtHealthPlan = new javax.swing.JTextField();

        btnUpload.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUpload.setText("Upload Image:");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblLicenseNo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblLicenseNo.setText("License No.:");

        txtBiometricIdentifier.setText(" ");

        txtFaxNo.setText(" ");

        lblVehicleIdentifier.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblVehicleIdentifier.setText("Vehicle Identifier");

        txtTelephoneNo.setText(" ");

        txtSSN.setText(" ");

        lblDeviceIdentifier.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblDeviceIdentifier.setText("Device Identifier:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Enter Details");

        txtEmailId.setText(" ");

        lblLinkedIn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblLinkedIn.setText("LinkedIn");

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblName.setText("Name:");

        lblIp.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblIp.setText("IP Adddress");

        lblGeographicData.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblGeographicData.setText("Geographic Data:");

        txtName.setText(" ");

        lblDob.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblDob.setText("DOB:");

        txtGeographicData.setText(" ");

        lblTelephoneNo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblTelephoneNo.setText("Telephone No.:");

        lblFaxNo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblFaxNo.setText("Fax No.");

        lblEmailID.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmailID.setText("Email Id:");

        lblSSN.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblSSN.setText("SSN");

        txtDeviceIdentifier.setText(" ");

        txtIp.setText(" ");

        lblMedicalRecord.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblMedicalRecord.setText("Medical Record No.:");

        txtLinkedIn.setText(" ");

        txtVehicleIdentifier.setText(" ");

        lblHealthPlan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblHealthPlan.setText("Health Plan :");

        txtBankAccount.setText(" ");

        txtLicenseNo.setText(" ");

        lblBankAccount.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblBankAccount.setText("Bank Account:");

        txtDob.setText(" ");

        lblBiometricIdentifier.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblBiometricIdentifier.setText("Biometric Identifier");

        txtMedicalRecord.setText(" ");

        txtHealthPlan.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblName)
                                        .addComponent(lblSSN)
                                        .addComponent(lblEmailID)
                                        .addComponent(lblFaxNo)
                                        .addComponent(lblTelephoneNo)
                                        .addComponent(lblMedicalRecord)
                                        .addComponent(lblDob)
                                        .addComponent(lblGeographicData))
                                    .addGap(53, 53, 53)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtMedicalRecord, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSSN, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtEmailId, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFaxNo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTelephoneNo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDob, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtGeographicData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(70, 70, 70)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblIp)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtIp, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblLinkedIn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblVehicleIdentifier)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtVehicleIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblBankAccount)
                                                .addComponent(lblHealthPlan)
                                                .addComponent(lblLicenseNo))
                                            .addGap(83, 83, 83)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtHealthPlan)
                                                .addComponent(txtBankAccount)
                                                .addComponent(txtLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblDeviceIdentifier)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtDeviceIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblBiometricIdentifier)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtBiometricIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addGap(301, 301, 301)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(txtUploadImage, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHealthPlan)
                    .addComponent(txtHealthPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeographicData)
                    .addComponent(txtGeographicData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBankAccount)
                    .addComponent(txtBankAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDob)
                    .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLicenseNo)
                    .addComponent(txtLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelephoneNo)
                    .addComponent(txtTelephoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVehicleIdentifier)
                    .addComponent(txtVehicleIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFaxNo)
                    .addComponent(txtFaxNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeviceIdentifier)
                    .addComponent(txtDeviceIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailID)
                    .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLinkedIn)
                    .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSN)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIp)
                    .addComponent(txtIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicalRecord)
                    .addComponent(txtMedicalRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBiometricIdentifier)
                    .addComponent(txtBiometricIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpload)
                    .addComponent(txtUploadImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File fImg = chooser.getSelectedFile();
        String imageFilename = fImg.getAbsolutePath();
        txtUploadImage.setText(imageFilename);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

            pr.setName(txtName.getText());
            pr.setGeographicData(txtGeographicData.getText());
            pr.setDob(txtDob.getText());
            pr.setTelephoneNo(txtTelephoneNo.getText());
            pr.setFaxNo(txtFaxNo.getText());
            pr.setEmail(txtEmailId.getText());
            pr.setSsn(txtSSN.getText());
            pr.setMedicalRecordNo(txtMedicalRecord.getText());
            pr.setHealthPlanBeneficiaryNo(txtHealthPlan.getText());
            pr.setBankaccountNo(txtBankAccount.getText());
            pr.setCertificateNo(txtLicenseNo.getText());
            pr.setVehicleIdentifier(txtVehicleIdentifier.getText());
            pr.setDeviceIdentifier(txtDeviceIdentifier.getText());
            pr.setLinkedin(txtLinkedIn.getText());
            pr.setIpAddress(txtIp.getText());
            pr.setBiometricIdentifier(txtBiometricIdentifier.getText());
            pr.setImageOfFace(txtUploadImage.getText());
            
            JOptionPane.showMessageDialog(null,"Details Entered Successfully");
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBankAccount;
    private javax.swing.JLabel lblBiometricIdentifier;
    private javax.swing.JLabel lblDeviceIdentifier;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEmailID;
    private javax.swing.JLabel lblFaxNo;
    private javax.swing.JLabel lblGeographicData;
    private javax.swing.JLabel lblHealthPlan;
    private javax.swing.JLabel lblIp;
    private javax.swing.JLabel lblLicenseNo;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMedicalRecord;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTelephoneNo;
    private javax.swing.JLabel lblVehicleIdentifier;
    private javax.swing.JTextField txtBankAccount;
    private javax.swing.JTextField txtBiometricIdentifier;
    private javax.swing.JTextField txtDeviceIdentifier;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtFaxNo;
    private javax.swing.JTextField txtGeographicData;
    private javax.swing.JTextField txtHealthPlan;
    private javax.swing.JTextField txtIp;
    private javax.swing.JTextField txtLicenseNo;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedicalRecord;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtTelephoneNo;
    private javax.swing.JTextField txtUploadImage;
    private javax.swing.JTextField txtVehicleIdentifier;
    // End of variables declaration//GEN-END:variables
}
